spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BloodDonationManagementSystem
    username: root
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  web:
    resources:
      static-locations: file:./uploads/


  mail:
    host: smtp.gmail.com
    port: 587
    username: jlakvidu@gmail.com
    password: pxgy wpef ktzj cyyy
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        transport:
          protocol: smtp

file:
  upload-dir: ./uploads